### ISSUE TITLE
Markdown, MD return wrong content type.

### ISSUE THREAD

**Issue by envygeeks** [discourse/mini_mime#12]
Even though this has been filed upstream, they've been slow to progress on the issue, even though an RFC exists for `text/markdown` being `md`, and `markdown`, and a pull-request exists upstream (see: https://github.com/mime-types/mime-types-data/issues/15, https://github.com/mime-types/mime-types-data/pull/13) this problem has yet to be fixed, so I'm hoping we can get a quick resolution here?

**Comment by SamSaffron** [comment]
@jeremy  what are your thoughts here, on one hand it is an easy one line change, but on the other hand we all agree it belongs upstream.

**Comment by jeremy** [comment]
Agree we should take care to track upstream, one-liner temptations aside 😄

Looks like the PR is essentially a bump from IANA upstream, suggesting that mime-types-data could use a more automated release process to keep up to date. Good way to contribute in permanently effective way?

/cc @halostatue

**Comment by halostatue** [comment]
Yes, I would happily consider PRs that improve the automation of mime-types-data, or even possibly finding a maintainer who has more time (most of my development time these days is not currently in Ruby).

**Comment by SamSaffron** [comment]
Yay, I just pulled it in from upstream going to do a new 1.0.1 version right now

**Comment by envygeeks** [comment]
I noticed that a couple of weeks ago when I was trying to update some sys mimetypes on Linux in an automated way and I had to do it all manually because they mix documentation and extensions >.> it was easier to just parse the HTML from Wikipedia and extract it from there.
