### ISSUE TITLE
Binary differences between mini_mime and mime-types

### ISSUE THREAD

**Issue by gmcgibbon** [discourse/mini_mime#22]
👋 I'm converting some code to use `mini_mime` instead of `mime-types` and I noticed a strange inconsistency in how types are labelled as binary. Here's the difference:

In `mime-types`:  `MIME::Types.of("a.css").first.binary? #=> false`
In `mini_mime`: `MiniMime.lookup_by_filename("a.css").binary? #> true`

This also happens with all other types that are labelled as `8bit` encoding in the db file. I think [this line](https://github.com/discourse/mini_mime/blob/087b9754d6231874bc2dfca9e7e7f63afcfdf7ad/lib/mini_mime.rb#L18) might be wrong.

Side note: it might also be cool to add a `#ascii?` method to check for non-binary encodings.

**Comment by jeremy** [comment]
mime-types uses the [same logic](https://github.com/mime-types/ruby-mime-types/blob/35403e85906d4a8c338cb994491726a7dda5cb16/lib/mime/type.rb#L69) to classify binary?/ascii? network transfer encoding; curious that these differ. Which MIME type does `MIME::Types.of("a.css").first` return?

(The method names are confusing here. This isn't indicating that the type itself is binary/ascii, but whether the type needs transfer encoding for non-8-bit-clean channels, such as attaching to an email message.)

**Comment by gmcgibbon** [comment]
I see. This is my mistake. I'm using an ancient version of `mime-types` that [does this](https://github.com/mime-types/ruby-mime-types/blob/ade226b48b6f7f4be5c72c33924f771365b00203/lib/mime/types.rb#L456). Many thanks for your help. 🙏
