### ISSUE TITLE
Extensions with multiple possible content types

### ISSUE THREAD

**Issue by gmcgibbon** [discourse/mini_mime#25]
In `mime-types`, I can do this:

```
MIME::Types.type_for("a.js") # => [
  #<MIME::Type: application/ecmascript>,
  #<MIME::Type: application/javascript>,
  #<MIME::Type: text/ecmascript>,
  #<MIME::Type: text/javascript>,
  #<MIME::Type: application/x-javascript>
]
```
but in `mini_mime`, it assumes only one return. This is specifically annoying for JavaScript because I can do:

```
MiniMime.lookup_by_filename("a.js") # =>
#<MiniMime::Info:0x000 @extension="js", @content_type="application/ecmascript", @encoding="base64">
```

which tells me `*.js` uses base64 encoding. Have we thought of these kind of use-cases and which one is actually correct?

I should also mention there is a [definition for `application/javascript`](https://github.com/discourse/mini_mime/blob/99ae9be5419bc95950a87089d1e2ea4c3413f3cb/lib/db/content_type_mime.db#L32) in the content type DB but you'll never reach it by looking up via extension.

**Comment by jeremy** [comment]
> Have we thought of these kind of use-cases and which one is actually correct?

Yes. Lookups return the highest priority, nonobsolete, registered match.
- https://github.com/discourse/mini_mime/blob/2194c2c76f8dd871249fd16e6caa4aa489ce357f/Rakefile#L42-L53
- https://github.com/mime-types/ruby-mime-types/blob/35403e85906d4a8c338cb994491726a7dda5cb16/lib/mime/type.rb#L142-L158
- 

> tells me `*.js` uses base64 encoding

Yes. Note that "encoding" indicates the content transfer encoding used for non-8bit-clean channels, like email attachments.

**Comment by paracycle** [comment]
Returning `application/ecmascript` for the `.js` extension seems to be a regression on the `mime-types-data` repo which is where I believe `mini_mime` gets its database from. 

You can find more details in the PR I opened regarding this: https://github.com/mime-types/mime-types-data/pull/20
