### ISSUE TITLE
Automatic updates from mime-types-data?

### ISSUE THREAD

**Issue by Fryguy** [discourse/mini_mime#30]
Would it be possible for this to be automatically built when mime-types-data changes?

I'm not sure exactly how it would work, but I think now that this repo is on GitHub Actions, it might be possible to react to a workflow event from the mime-types-data repo, or perhaps less elegantly, just run a scheduled cron on some interval.

I can envision a task that, when run, automatically runs `bundle exec rake rebuild_db`, and if there are changes creates a pull request.

**Comment by SamSaffron** [comment]
I would love to have something like this set up, feel free to give it a shot using github actions. 

I just checked now and we are still up-to-date.

**Comment by Fryguy** [comment]
Closed via #33
