### ISSUE TITLE
image/x-bmp is wrong, use image/bmp instead

### ISSUE THREAD

**Issue by wtn** [discourse/mini_mime#43]
`image/bmp` is documented here: https://www.iana.org/assignments/media-types/image/bmp

**Comment by wtn** [comment]
I reported this issue upstream.

**Comment by CvX** [comment]
This gem takes its mime data from https://github.com/mime-types/mime-types-data, see: https://github.com/discourse/mini_mime/blob/main/.github/workflows/db.yml

**Comment by halostatue** [comment]
This has also been reported as mime-types/mime-types-data#48, which has been resolved with the release of 3.2022.0105.

**Comment by tagliala** [comment]
I think this has been fixed by #45, but a new release of this gem is still pending

**Comment by SamSaffron** [comment]
should be fixed in current. 

https://github.com/discourse/mini_mime/blob/ad29352bf7b8fa547ea3058f2e97f3e8496f034a/lib/db/ext_mime.db#L73-L73
